# Generated by Django 2.1 on 2018-10-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='projects/')),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=255)),
            ],
        ),
    ]
