# Generated by Django 2.1 on 2018-10-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20181005_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('desktop', 'desktop'), ('websites', 'websites'), ('mobile', 'mobile'), ('IoT', 'IoT'), ('.coming soon...', 'coming soon...')], default='desktop', max_length=10, null=True),
        ),
    ]
