# Generated by Django 2.1 on 2018-09-29 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0002_front_page_about_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='front_page',
            name='about_image',
            field=models.ImageField(null=True, upload_to='front_page_images/'),
        ),
    ]
