# Generated by Django 2.1 on 2018-09-29 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0003_front_page_about_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='front_page',
            name='programming_language_image',
            field=models.ImageField(null=True, upload_to='front_page_images/'),
        ),
    ]
