# Generated by Django 2.1 on 2018-09-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prg_languages', '0004_auto_20180902_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prg_language',
            name='image',
            field=models.ImageField(height_field='image_height', upload_to='prg_language/', width_field='image_width'),
        ),
    ]
