# Generated by Django 2.1 on 2018-09-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prg_languages', '0005_auto_20180902_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='prg_language',
            name='image_height',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='prg_language',
            name='image_width',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
