# Generated by Django 2.1 on 2018-10-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prg_languages', '0006_auto_20180902_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prg_language',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='prg_language',
            name='image_width',
        ),
        migrations.AddField(
            model_name='prg_language',
            name='title',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prg_language',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
