# Generated by Django 2.1 on 2018-10-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prg_languages', '0007_auto_20181002_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='prg_language',
            name='image_height',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='prg_language',
            name='image_width',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='prg_language',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
