# Generated by Django 2.1 on 2018-10-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prg_languages', '0013_auto_20181002_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='prg_language',
            name='source_link',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
