# Generated by Django 2.1 on 2018-10-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image_thumbnail',
            field=models.ImageField(null=True, upload_to='blogimages/'),
        ),
    ]
