# Generated by Django 2.1 on 2018-09-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Social_Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='social_network_images/')),
                ('name', models.CharField(max_length=75)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
