# Generated by Django 2.1 on 2018-10-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_provided', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_provided',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
